version: '3'

services:

  sqlserver2017:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: sql2017
    ports:
        - "8383:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=D8ydAKoaE01K8CajreUk
      - MSSQL_PID=Developer
    volumes:
      - sqlserver-data:/var/opt/mssql
    logging:
      options:
        max-size: "10m"
        max-file: "10" 
        
volumes:
  sqlserver-data: